version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Entered the INSTAL phase
      - echo something something
      - yum update -y
      - yum install jq git -y -q
      - echo Configuring aws cli...
      - pip3 install awsebcli --upgrade
      - pip install --upgrade awscli
      - aws configure set default.region us-east-1
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Current directory is $CODEBUILD_SRC_DIR
      - ls -la
      - "export dirname=${PWD##*/}"
      - echo Directory name $dirname
      - echo Installing packeges using pip3...
      - make pre-install
      - echo "====================="
      - echo lint lambda source code ...
      - make lint
      - echo lint cloudformation template ...
      - cfn-lint template.yml
      - echo validate SAM template ...
      - sam validate --template-file template.yml
      - echo run unit tests ...
      - make test
  build:
    commands:
      - echo "====================="
      - echo sam build ...
      - sam build
      - echo packege code ...
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket $S3_BUCKET_NAME
  post_build:
    commands:
      - echo "====================="
      - echo project was successfully built and packaged in s3 bucket - $S3_BUCKET_NAME
reports:
  pytest-reports:
    files:
      - "**/*"
    base-directory: "reports"
artifacts:
  files:
  # export artifacts needed for deployments to an S3 bucket
    - package.yml